### ISSUE TITLE
Changing mpv media-title by other scripts -> playlist entries will be overwritten

### ISSUE THREAD

**Issue by hubblec4** [tomasklaen/uosc#793]
Hi tomasklaen

First, many thanks for this awesome project.

I use in my [mpvMatroska](https://github.com/hubblec4/mpvMatroska) project a method to change the media-title.

But this changes the names of the entries in the playlist. Here the [issue](https://github.com/hubblec4/mpvMatroska/issues/1).

```lua
local mp = require "mp"

local counter = 1

mp.register_event("file-loaded", function()
	mp.set_property("force-media-title", tostring(counter))
	
	counter = counter +1
end)
```

With this small test script you can see the changes in the playlist.

**Comment by christoph-heinrich** [comment]
We're merely showing the title of the playlist item, how is that weird?

**Comment by hubblec4** [comment]
Because after a file changing (and mpvMatroska or the test script sends a new media-title) the current playlist item gets the name of the previous playlist item.

The media-title is correct shown in the main mpv window.

**Comment by christoph-heinrich** [comment]
You might want to set `file-local-options/force-media-title` instead.

**Comment by christoph-heinrich** [comment]
> But this is not a perfect solution, because the mpv media title is not changed.

`media-title` does actually change, but the uosc doesn't notice because we don't get a notification. I'm currently working on a PR for mpv to fix this).

The window title gets updated because it doesn't rely on those notifications and uses a polling based solution instead.

The title in the builtin osc should change when you cycle though the osc visibility with <kbd>del</kbd>. That is because it also doesn't rely on those notifications.

> For me is it not clear why changing the media-title changes title filename titles in a selection list?

Playlist listings usually show the title of the playlist item if available with a fall back to the filename.

When you open a file that doesn't yet have a title set in the playlist and it's title becomes known, then mpv remembers that title for that playlist item and as a result that title shows up in the list.

**Comment by hubblec4** [comment]
Many thanks for your explanations and good to see that you opened a PR for that issue.

When this is fixed the property `media-title` will work and I have to change this in my script from

```lua
mp.set_property("force-media-title", tostring(counter))
```

to

```lua
mp.set_property("media-title", tostring(counter))
```

is this correct?

**Comment by christoph-heinrich** [comment]
> When this is fixed the property `media-title` will work and I have to change this in my script from
> 
> ```lua
> mp.set_property("force-media-title", tostring(counter))
> ```
> 
> to
> 
> ```lua
> mp.set_property("media-title", tostring(counter))
> ```
> 
> is this correct?

No, you should continue to use `mp.set_property("local-file-options/force-media-title", counter)` (no need for tostring afaik)

**Comment by hubblec4** [comment]
Ahh OK, very interesting, because I have nothing found to `local-file-options/force-media-title` [here](https://mpv.io/manual/master/#property-list)

Sorry, I'm new to mpv.

**Comment by christoph-heinrich** [comment]
Sorry it's `file-local-options/force-media-title`, I got it the wrong way around.

**Comment by hubblec4** [comment]
OK yes. You had posted it above correct.

But I can't also find nothing for `local-file-options`.

Is this a special option and can be combined with other things.

Back to the issue:
Lets say it is fixed. It will be interesting if the playlist entry names are correct changed.
At the moment is the new selected list item overwritten with the prior selected item name.

**Comment by christoph-heinrich** [comment]
> At the moment is the new selected list item overwritten with the prior selected item name.

That still happens even when you prefix it with `file-local-options` ?

**Comment by hubblec4** [comment]
No, there is no change in the playlist.

**Comment by christoph-heinrich** [comment]
> No, there is no change in the playlist.

Then I have no idea why it would still assign the title to the wrong playlist item. Above you said that it helped :shrug:

**Comment by hubblec4** [comment]
>  Above you said that it helped

Sorry when I have not fully and correct explained. It helps so far that the playlist items no longer are changed, and the media-title is correct shown in the mpv main window.

But now there is no change for the Top-Bar title (or built-in OSC media-title), which for me is more important, but for other users are the playlist items also important.

When an mkv has multiple editions, I add the current played edition name to the mkv-Title (if present) or the filename.

**Comment by tomasklaen** [comment]
From what I gather there's not much to do on our side, so I'm gonna close this. Feel free to discuss further if there's more info
